name: Testing Functionality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      working-directory: ./Demo-Testing-Project
      run: dotnet restore

    - name: Build
      working-directory: ./Demo-Testing-Project
      run: dotnet build --no-restore

    - name: Run tests
      working-directory: ./Demo-Testing-Project
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test --verbosity normal
